FROM ghcr.io/graalvm/native-image:22.3.1 as build

WORKDIR /workspace/app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

ARG BUILD_ARG
ENV PROJECT_ID=$BUILD_ARG
RUN ./mvnw -Pnative clean native:compile -DskipTests=true
#ENTRYPOINT ["./target/gke-spring"]

#FROM gcr.io/distroless/java-base-debian11:debug
FROM eclipse-temurin:17-jre
ARG BUILD_ARG
ENV PROJECT_ID=$BUILD_ARG
WORKDIR /app
COPY --from=build /workspace/app/target/gke-spring .
ENTRYPOINT ["./gke-spring"]