apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: spanner-client@noogler-2.iam.gserviceaccount.com
  name: k8s-spanner
#gcloud iam service-accounts add-iam-policy-binding spanner-client@noogler-2.iam.gserviceaccount.com --role roles/iam.workloadIdentityUser --member "serviceAccount:noogler-2.svc.id.goog[default/k8s-spanner]"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-front-deploy
  labels:
    app: spring-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-front
  template:
    metadata:
      labels:
        app: spring-front
    spec:
      serviceAccountName: k8s-spanner
      containers:
      - name: spring-front-container
        image: asia-northeast1-docker.pkg.dev/noogler-2/app/gke-spring:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PROJECT_ID
          value: noogler-2
        startupProbe:
          httpGet:
            path: /item
            port: 8080
          failureThreshold: 15
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /hostinfo
            port: 8080
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-back-deploy
  labels:
    app: spring-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-back
  template:
    metadata:
      labels:
        app: spring-back
    spec:
      serviceAccountName: k8s-spanner
      containers:
      - name: spring-back-container
        image: asia-northeast1-docker.pkg.dev/noogler-2/app/gke-spring:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PROJECT_ID
          value: noogler-2
        startupProbe:
          httpGet:
            path: /item
            port: 8080
          failureThreshold: 15
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /hostinfo
            port: 8080
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-front-service
spec:
  type: LoadBalancer
  selector:
    app: spring-front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-back-service
spec:
  type: LoadBalancer
  selector:
    app: spring-back
  ports:
  - name: p1
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: p2
    protocol: TCP
    port: 8080
    targetPort: 8080
