apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-spanner
#gcloud projects add-iam-policy-binding projects/noogler-2 --role=roles/spanner.databaseUser --member=principal://iam.googleapis.com/projects/896536828389/locations/global/workloadIdentityPools/noogler-2.svc.id.goog/subject/ns/default/sa/k8s-spanner --condition=None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-front-deploy
  labels:
    app: spring-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-front
  template:
    metadata:
      labels:
        app: spring-front
    spec:
      serviceAccountName: k8s-spanner
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      terminationGracePeriodSeconds: 25
      containers:
      - name: spring-front-container
        image: asia-northeast1-docker.pkg.dev/noogler-2/app/gke-spring:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PROJECT_ID
          value: noogler-2
        startupProbe:
          httpGet:
            path: /item
            port: 8080
          failureThreshold: 15
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /hostinfo
            port: 8080
        readinessProbe:
          httpGet:
            path: /item
            port: 8080
        resources:
          requests:
            memory: "420Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-back-deploy
  labels:
    app: spring-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-back
  template:
    metadata:
      labels:
        app: spring-back
    spec:
      serviceAccountName: k8s-spanner
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      terminationGracePeriodSeconds: 25
      containers:
      - name: spring-back-container
        image: asia-northeast1-docker.pkg.dev/noogler-2/app/gke-spring:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PROJECT_ID
          value: noogler-2
        startupProbe:
          httpGet:
            path: /item
            port: 8080
          failureThreshold: 15
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /hostinfo
            port: 8080
        readinessProbe:
          httpGet:
            path: /item
            port: 8080
        resources:
          requests:
            memory: "420Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-front-service
spec:
  type: LoadBalancer
  selector:
    app: spring-front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-back-service
spec:
  type: LoadBalancer
  selector:
    app: spring-back
  ports:
  - name: p1
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: p2
    protocol: TCP
    port: 8080
    targetPort: 8080
